version: "3"
services:
  webserver:
    image: bala976/practice:bala
    ports:
      - 80:80
    environment:
      - department=dev

  backend:
    image: bala976/practice:alpine
    ports:
      - 8080:80
      
  web:
    image: nginx
    ports:
      - "81:80"
  
  m1:
    image: httpd
    ports:
      - "85:80"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/